
---
- hosts: localhost
  connection: local
  vars:
    project_name: "myproject"
    username: "system:admin"
    password: "lala"
    master_url: "https://127.0.0.1:8443/"
  tasks:

  - name: login as {{ username }} (must be cluster-admin)
    shell: "oc login -u system:admin"
    #shell: "oc login -u {{ username }} -p {{ password }} {{ master_url }}"
    #shell: oc login https://127.0.0.1:8443 --token=FwgcAV8Wz0TPuLIQYzNY9kKvLSoMS5MUvA0UzVXFl9s

  - name: Add permissions
    shell: "oc adm policy add-scc-to-user {{ item }} -z default -n {{ project_name }}"
    with_items:
      - anyuid
      - privileged


  - pause: seconds=20

  - name: Let chaincode process give it to its best
    shell: >
      oc -n "{{ project_name }}" exec fabric-tools -- bash -c '/fabric/scripts/deployCC.sh'
