kind: PersistentVolume
apiVersion: v1
metadata:
  name: fabric-pv20
  labels:
    type: local
    name: fabricfiles20
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/fabric
    server: storage.local.parisi.biz
    readOnly: false
