# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        CommonName: "orderer"
      - Hostname: orderer2
        CommonName: "orderer2"
      - Hostname: orderer3
        CommonName: "orderer3"
      - Hostname: orderer4
        CommonName: "orderer4"
      - Hostname: orderer5
        CommonName: "orderer5"

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        CommonName: "org1peer0"
      - Hostname: peer1
        CommonName: "org1peer1"
    Users:
      Count: 1
    
  # ---------------------------------------------------------------------------
  # Org2: 
  # ---------------------------------------------------------------------------
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        CommonName: "org2peer0"
      - Hostname: peer1
        CommonName: "org2peer1"
    Users:
      Count: 1
