apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: org1peer0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: org1peer0
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc
          # raus mit external launcher
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: peer
        image: udosson/udosson:hyperledger-fabric-peer-golang-jq
        command: ["sh", "-c", "peer node start", "cp -r /fabric/config/core.yaml /etc/hyperledger/fabric/"]
        networks:
        - byfn
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        - name: CORE_PEER_ID
          value: org1peer0:com
        - name: CORE_PEER_ADDRESS
          value: org1peer0:30110
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30110
        - name: CORE_PEER_CHAINCODEADDRESS
          value: org1peer0:30111
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:30111
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: org1peer1:30110
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: org1peer0:30110
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_MSPCONFIGPATH
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/org1peer0/msp/
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/org1peer0/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/org1peer0/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/org1peer0/tls/ca.crt
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: 0.0.0.0:5984
        - name: FABRIC_CFG_PATH
          value: /fabric/config/
        - name: CORE_CHAINCODE_EXECUTETIMEOUT
          value: 300s
        - name: GODEBUG
          value: "netdns=go"
        - name: dns_search 
          value: " ."
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
          #TODO dockersocket raus mit External Launcher
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
      - name: couchdb
        image: hyperledger/fabric-couchdb:latest
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        - name: COUCHDB_USER
          value: ""
        - name: COUCHDB_PASSWORD
          value: ""
