apiVersion: v1
kind: Service
metadata:
  name: blockchain-org2peer0
  labels:
    run: blockchain-org2peer0
spec:
  type: ClusterIP 
  selector:
    name: blockchain-org2peer0
  ports:
  - protocol: TCP
    port: 30110
    name: grpc
  - protocol: TCP
    port: 30111
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
