apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer2
  labels:
    run: blockchain-orderer2
spec:
  type: ClusterIP
  selector:
    name: blockchain-orderer2
  ports:
  - protocol: TCP
    port: 31010
    name: grpc
