apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderer4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orderer4
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc
      containers:
      - name: orderer
        image: hyperledger/fabric-orderer:2.0
        command: ["orderer"]
        networks:
          - byfn
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        - name: ORDERER_CFG_PATH
          value: /fabric/
        - name: CONFIGTX_ORDERER_ADDRESSES
          value: "orderer4:31010"
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: "31010"
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer4/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer4/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer4/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: /fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer4/tls/ca.crt
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: /fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer4/tls/server.key
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: /fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer4/tls/server.crt
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: /fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer4/tls/ca.crt
        - name: GODEBUG
          value: "netdns=go"
        - name: ORDERER_GENERAL_BOOTSTRAPFILE
          value: /fabric/channel-artifacts/genesis.block
        - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
          value: file
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
