apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer3
  labels:
    run: blockchain-orderer3
spec:
  type: ClusterIP
  selector:
    name: blockchain-orderer3
  ports:
  - protocol: TCP
    port: 31010
    name: grpc
