apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
  volumes:
  - name: fabricfiles
    persistentVolumeClaim:
      claimName: fabric-pvc
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabric-tools
      image: hyperledger/fabric-tools:2.0
      imagePullPolicy: Always
      stdin: true 
      tty: true
      #       command: ["/bin/bash", "-c", "sleep 48h"]
      command: ["/bin/bash", "-c", "sleep 48h"]
      env:
        - name: CORE_PEER_ID
          value: fabric-tools
        - name: CORE_PEER_ADDRESS
          value: org1peer0:30110
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/org1peer0/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/org1peer0/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/org1peer0/tls/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/org1peer0/msp/
        - name: TZ
          value: "Europe/Amsterdam"
        - name: FABRIC_CFG_PATH
          value: "/fabric"
        - name: GOPATH
          value: /opt/gopath
        - name: GOPATH
          value: /fabric
        - name: GODEBUG
          value: "netdns=go"
      volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
