apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
  volumes:
  - name: fabricfiles
    persistentVolumeClaim:
      claimName: fabric-pvc
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabric-tools
      image: hyperledger/fabric-tools:2.0
      imagePullPolicy: Always
      #       command: ["/bin/bash", "-c", "sleep 48h"]
      command: ["sh", "-c", "sleep 48h"]
      env:
      - name: TZ
        value: "Europe/Amsterdam"
      - name: FABRIC_CFG_PATH
        value: "/fabric"
      - name: FABRIC_LOGGING_SPEC
        value: INFO
      volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
